name: Manage Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling
        id: typos
        uses: crate-ci/typos@v1.16.23
        with:
          write-changes: false
        continue-on-error: true

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './docs/**/*.md' --format markdown
          output: ./lychee.md
          fail: true
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment Link Check Results
        if: always()
        uses: actions/github-script@v7
        env:
          TYPOS_OUTPUT: ${{ steps.typos.outputs.output }}
        with:
          script: |
            const fs = require('fs');
            const linkCheckOutput = fs.readFileSync('./lychee.md', 'utf8');

            const output = `
            Thanks for submitting a pull request! ðŸ‘

            Checks:
            > Check Markdown links
            <details>
            <summary>Click to expand</summary>

              \`\`\`markdown
              ${linkCheckOutput}
              \`\`\`
            </details>

            > Check spelling
            <details>
            <summary>Click to expand</summary>

              \`\`\`
              ${process.env.TYPOS_OUTPUT}
              \`\`\`
            </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: output
            });
